<?xml version="1.0"?>
<package format="3">
  <name>ros2_ai_debugger</name>
  <version>0.1.0</version>
  <description>AI-assisted diagnostics and troubleshooting for ROS 2 systems.</description>
  <maintainer email="projecthumanoidx@gmail.com">Arjunros</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>ros2cli</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
