"""Markdown report, designed to be pasted into a GitHub issue."""
from __future__ import annotations

from ros2_ai_debugger.models import Finding
from ros2_ai_debugger.reporting.report import Report


def render_markdown(report: Report) -> str:
    s, env = report.snapshot, report.snapshot.environment
    icon = {None: "✅", 0: "ℹ️", 1: "⚠️", 2: "❌"}[None if report.overall() is None else int(report.overall())]
    out = [
        "# ROS 2 AI Diagnostic Report", "",
        f"**Overall:** {icon} {report.overall_label()}", "",
        "## Environment", "",
        "| | |", "|---|---|",
        f"| ROS 2 distribution | {env.ros_distro or 'unknown'} |",
        f"| ROS_DOMAIN_ID | {env.ros_domain_id if env.ros_domain_id is not None else 'unset (default 0)'} |",
        f"| RMW implementation | {env.rmw_implementation or 'unset (default)'} |",
        f"| ROS_LOCALHOST_ONLY | {env.localhost_only or 'unset'} |",
        f"| OS | {env.os_name or 'unknown'} |",
        f"| Python | {env.python_version or 'unknown'} |",
        f"| ros2-ai-debugger | {report.tool_version} |",
        f"| Collected at | {report.generated_at} |", "",
        "## System snapshot", "",
        f"- Nodes: {len(s.nodes)}", f"- Topics: {len(s.topics)}",
        f"- Services: {len(s.services)}", f"- Actions: {len(s.actions)}",
        f"- TF frames: {len(s.tf.frames()) if s.tf else 'not collected'}",
    ]
    if s.system:
        r = s.system
        out.append(f"- CPU {_pct(r.cpu_percent)}, memory {_pct(r.memory_percent)}, "
                   f"disk {_pct(r.disk_percent)} ({r.cpu_count} cores)")
    out += ["", "<details><summary>Nodes and topics</summary>", "", "**Nodes**", ""]
    out += [f"- `{n.name}`" for n in s.nodes] or ["- (none)"]
    out += ["", "**Topics** (publishers / subscribers)", ""]
    out += [f"- `{t.name}` ({len(t.publishers)} / {len(t.subscribers)})" for t in s.topics] or ["- (none)"]
    out += ["", "</details>", "", "## Detected problems", ""]
    if not report.findings:
        out += ["No problems detected by the enabled checks.", ""]
    n = 0
    for f in report.findings:
        n += 1
        out += _finding(n, f)
    out += _ai(report)
    if report.all_commands():
        out += ["## Relevant commands", "", "All commands are read-only.", "", "```bash"]
        out += report.all_commands() + ["```", ""]
    if s.collection_errors:
        out += ["## Collection notes", ""] + [f"- {e}" for e in s.collection_errors] + [""]
    out += ["---",
            f"*Generated by [ros2-ai-debugger](https://github.com/Arjunros/ros2-ai-debugger) "
            f"{report.tool_version}. Read-only diagnosis; observations are collected facts, "
            f"causes are inferences." + (" Hostnames, IP addresses, usernames and paths were masked." if report.redacted else "") + "*"]
    return "\n".join(out) + "\n"


def _pct(v: float | None) -> str:
    return "n/a" if v is None else f"{v:.1f}%"


def _finding(n: int, f: Finding) -> list[str]:
    out = [f"### Finding #{n}: {f.problem}", "",
           f"- **Severity:** {f.severity.label}", f"- **Component:** `{f.component}`",
           f"- **Confidence:** {f.confidence:.2f} (heuristic, for the top possible cause)",
           f"- **Source:** {f.source}", "", "**Observed**", ""]
    out += [f"- {o}" for o in f.observed] or ["- (nothing specific)"]
    if f.possible_causes:
        out += ["", "**Inferred (possible causes, not confirmed)**", ""]
        out += [f"{i}. {c}" for i, c in enumerate(f.possible_causes, 1)]
    if f.recommended_checks:
        out += ["", "**Recommended checks**", "", "```bash"] + f.recommended_checks + ["```"]
    return out + [""]


def _ai(report: Report) -> list[str]:
    ai = report.ai
    out = ["## AI analysis", ""]
    if ai.mode == "used":
        out.append(f"Provider: {ai.detail}. AI output is validated against the snapshot but is not verified.")
        if ai.summary:
            out += ["", f"> {ai.summary}"]
        if ai.missing_information:
            out += ["", "**Missing information**", ""] + [f"- {m}" for m in ai.missing_information]
        if ai.warnings:
            out += ["", "**Unsupported AI output removed by validation**", ""] + [f"- {w}" for w in ai.warnings]
    else:
        out.append(f"Not used ({ai.mode}{': ' + ai.detail if ai.detail else ''}). Findings above are rule-based only.")
    return out + [""]
